name: Demo pipeline

on: [push,  workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo...
      uses: actions/checkout@v2

    - name: "No input. first step makes a file"
      run: |
        ls -ltr
        echo "step 1">artifact.txt
        mkdir step1
        cp -v  artifact.txt ./step1

    - name: "Step 2"
      run: |
        ls -ltr
        echo "step 2 stuff"
        exit 0

    - name: Step Three
      run: |
        ls -ltr
        cd ./step1
        cat artifact.txt
        exit 1
