name: Demo pipeline

on: [push,  workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repo...
      uses: actions/checkout@v2

    - name: "No input. first step makes a file"
      run: |
        pwd
        ls -ltr
        mkdir step1
        echo "step 1">step1/artifact.txt

    - name: "Step 2"
      run: |
        pwd
        ls -ltr
        echo "step 2 stuff"
        exit 0

    - name: Step Three
      run: |
        pwd
        ls -ltr
        cd ./step1
        cat artifact.txt
        exit 0
