name: Demo pipeline

on: [push,  workflow_dispatch]

jobs:
  demo-1:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repo...
      uses: actions/checkout@v2

    - name: "Centrifuge(src) => [capabilities, primitives]"
      run: |
        pwd
        ls -ltr
        mkdir -v capabilities
        mkdir -v primitives
        echo "step 1">capabilities/artifact.txt
        cd capabilities

    - name: "ChainReactor(capabilities) => chains"
      run: |
        cd capabilities
        pwd
        echo "capabilities stuff"
        exit 0

    - name: "Mitigations(primitives)"
      run: |
        pwd
        echo "mitigations stuff"
        exit 0
