name: Demo pipeline

on: [push,  workflow_dispatch]

jobs:
  demo-1:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repo...
      uses: actions/checkout@v2

    - name: "Centrifuge(src) => [capabilities, primitives]"
      run: |
        pwd
        ls -ltr
        mkdir -v capabilities
        mkdir -v primitives
        echo "step 1">capabilities/artifact.txt
        cd capabilities

    - name: "Step 2"
      run: |
        pwd
        ls -ltr
        echo "step 2 stuff"
        exit 0

    - name: Step Three
      run: |
        pwd
        ls -ltr
        cd ./step1
        cat artifact.txt
        exit 0
