on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: noah-de/junk-actions-test@v1

        with:
          who-to-greet: 'Harold of the rocks'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
  next:
    runs-on: ubuntu-latest
    name: Dependency
    needs: hello_world_job
    steps:
      - run: echo "special step"
