name: several jobs 
on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - uses: actions/checkout@v3
      - id: foo
        uses: noah-de/junk-actions-test@v1

        with:
          who-to-greet: 'Harold of the rocks'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  next:
    runs-on: ubuntu-latest
    name: Dependency
    needs: first_job
    steps:
      - name: installing required packages
        run: sudo apt-get install git gcc g++ make uuid-dev python-is-python3 build-essential nasm iasl libx11-dev libxv-dev gdb

  centrifuge:
    runs-on: ubuntu-latest
    needs: next
    steps:
      # Centrifuge accepts Source code and produces two outputs for downstream processes
      - name: "Centrifuge(src) => [capabilities, primitives]"
        run: |
          pwd
          ls -ltr
          echo "discovering capabilities" $(mkdir -v capabilities)
          echo "capabilities">capabilities/artifact.txt
          echo "producing primatives:" $(mkdir -v primitives)
          echo "primitives ">primitives/artifact.txt
      - name: 'upload artifact'
        uses: actions/upload-artifact@v3
        with:
          name: primitives
          path: primitives

  other:
    runs-on: ubuntu-latest
    needs: [next,centrifuge]
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      # Centrifuge accepts Source code and produces two outputs for downstream processes
      - name: other-job
        run: |
          pwd
          ls -ltr
